name: marvelphazero
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15  
  provider: ^6.0.1 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  connectivity_plus: ^2.2.0
  dio: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-BoldItalic.ttf
        - asset: fonts/DMSans-Italic.ttf
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-MediumItalic.ttf
        - asset: fonts/DMSans-Regular.ttf    
 

 